spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/webExampleTwo?serverTimezone=UTC&characterEncoding=UTF-8&createDatabaseIfNotExist=true
    username: root
    password: root
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
  jpa:
    hibernate:
      show-sql: true
      format_sql: true
      ddl-auto: create
